### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by daveverwer** [ptsochantaris/maintini#1]
Hey Paul, I see you have a documentation link in the README file, but there's no `.spi.yml` file so we are not yet generating it. Was it there previously or am I a little early?

**Comment by ptsochantaris** [comment]
Oh, I'm an idiot, I forgot to include that, and I created those documentation links ahead-of-time because I had submitted the packages late to the index. Totally my bad, will commit one now - thanks for the nudge. I think the same applies to the PopTimer package as well, will fix.

**Comment by ptsochantaris** [comment]
Have added `.spi.yml` to both repos now #whoops - thanks again for spotting that!

**Comment by daveverwer** [comment]
That's great, thanks so much for fixing it! We should notice that tag in a few hours (we have a 24h cooldown on changes to default branches) and it should build automatically then.

**Comment by ptsochantaris** [comment]
Brilliant, thanks for the update, I'll be sure to try and remember the `.spi.yml` file in the future (or better yet, just not add links in advance late at night :))

**Comment by ptsochantaris** [comment]
This doesn't seem to have worked unfortunately - am I doing something wrong? I added the file and even upped the release tag a while ago but it seems the doc link still doesn't work.

**Comment by daveverwer** [comment]
Hi Paul, and apologies for this not working as expected! We're dealing with a quite serious (and unprecedented) issue with the package index this week ([detailed here](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2571)) and as a result of that, we have a huge backlog of packages awaiting our compatibility build testing process. Unfortunately, our documentation generation process runs after that build process.

There's nothing you need to do, unless you still don't have docs when [this page](https://swiftpackageindex.com/ptsochantaris/maintini/builds) fills itself in. We should be done in a few more days. I'd check again on Monday.

Apologies again for this!

**Comment by ptsochantaris** [comment]
No problem @daveverwer - I wasn't aware of the issue, thanks for your quick reply to let me know. Good luck with the recovery - there's definitely no hurry on my end, I was just worried I had done something silly or overlooked something obvious 👍

**Comment by daveverwer** [comment]
Thanks Paul!

**Comment by ptsochantaris** [comment]
All looks great, will close the issue now, thanks again for spotting the issue and letting me know 👍

**Comment by daveverwer** [comment]
The system works! 🚀

Apologies again for the delay this time, it was a tricky week with the other bug!
