### ISSUE TITLE
Is this library viable for handling tasks that takes upto 10 seconds?

### ISSUE THREAD

**Issue by pradeepb28** [ptsochantaris/maintini#2]
Is this library viable for handling tasks that takes upto 10 seconds? (The task is related to network request)

Thanks!

**Comment by ptsochantaris** [comment]
Hi, the library itself will ask the OS to keep the app active in the background as long as possible. Usually on iOS, under normal conditions this is around 30 seconds, but low battery mode may mean this request is denied, or if the system is under moderate load it can be closer to 10 seconds. In general there is no limit on the side of this framework, so if the OS will give ten seconds then that should work fine.

(Slightly off-topic but related: If you're making a request that can take 10 seconds you may want to consider background URL sessions for those data transfers)

**Comment by ptsochantaris** [comment]
I hope this helps! Closing this for now. Please feel free to re-open or open new issues if you have more questions.
